### ISSUE TITLE
Deps outdated

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/farmbot-js#138] opened 2021-04-02 04:41 UTC
Updated **farmbot** latest from NPMJS.com ( v13.1.0 ) and then did `npm install` to a fresh directory for my app.
Got trouble with **jest** and **ts-jest** versioning :1234: as picture shows . . also **mqtt** has had a major version update (f.w.i.w.)

![Screenshot from 2021-04-02 15-19-43](https://user-images.githubusercontent.com/1224439/113380997-87bdbb00-93c9-11eb-8eb7-366797ad3814.png)

**Comment by RickCarlino** [comment] 2021-04-02 12:49
I guess it is time for a dep upgrade. I've added it to my TODO list.

**Comment by SupposedlySam** [comment] 2021-07-01 15:37
Just pulled down the repo and ran `npm audit fix --force`. It updated the dependencies from
```json
"dependencies": {
    "mqtt": "^3.0.0",
    "ts-jest": "^24.3.0"
  },
```
to 
```json
"dependencies": {
    "mqtt": "^4.2.8",
    "ts-jest": "^27.0.3"
  },
```
but running `npm run test` per the README resulted in some failures
```
Test Suites: 5 failed, 4 passed, 9 total
Tests:       4 failed, 6 passed, 10 total
Snapshots:   0 total
Time:        12.635 s
```

Any updates on the dependency upgrades and test fixes @RickCarlino?

**Comment by RickCarlino** [comment] 2021-07-02 02:27
@SupposedlySam I am suspicious that the issue is with the test suite rather than any actual breakage (a good starting point for anyone interested in contributing).

I have pushed the dep updates to the `main` branch if you would like to take a look. I won't have time to do QA on this soon (and thus, I cannot publish it to NPM right now) but if you are willing to take a look it is up.

**Comment by RickCarlino** [comment] 2021-07-02 02:50
@SupposedlySam I have published `14.2.1-rc.0` on NPM if you would like to take a look.

**Comment by RickCarlino** [comment] 2021-07-02 13:13
@jsimmonds2 @SupposedlySam Update 3: It looks like this update may not have been a very big one after all. It seems to work fine on my FarmBot device, so I went ahead and published `farmbot@14.2.1`.

Closing this issue.

**Closed by RickCarlino** 2021-07-02 13:13 UTC

**Comment by SupposedlySam** [comment] 2021-07-02 14:23
Are there any additional requirements besides pulling down the repo, running `npm install` and then `npm run test`? I'm running on a Macbook Pro and do not have a farmbot device.

**Comment by RickCarlino** [comment] 2021-07-02 14:35
@SupposedlySam `npm install farmbot@14.2.1` should be adequate if you are trying to use FarmBotJS.

If you are trying to do local development of FBJS, `npm install` and `npm run test` should be all you need to do, though the build/tests are currently broken (and have been for some time AFAIK).

**Comment by RickCarlino** [comment] 2021-07-02 14:36
Also, as a side note, if you own a Raspberry Pi 3 and an Arduino device, you can install FBOS onto a "headless" RPI (with Arduino attached) if you would like to do local testing. In your web app account, you need to select v1.2 as your model type.

This is very useful for local testing.
